apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-cert-secret
  creationTimestamp: null
  name: ocs-client-operator-webhook-server
spec:
  ports:
  - name: server
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook-server
  type: ClusterIP
status:
  loadBalancer: {}
