apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-cert-secret
  name: webhook-server
  namespace: system
spec:
  ports:
  - name: server
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook-server
  type: ClusterIP
