---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storageclients
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook
subjects:
  - kind: ServiceAccount
    name: webhook
    namespace: system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: webhook
  namespace: system
---
